version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    assignees:
      - "EtK2000"
    commit-message:
      prefix: "Maven"
      include: "scope"
    directory: "/"
    reviewers:
      - "EtK2000"
    schedule:
      interval: "monthly"
